# When a tag matching a semver number (like `1.1.0`) is pushed, then try to publish the version to bintray and create the matching release in Github
name: CI-Release
on:
  push:
    tags:
      - '*-RELEASE'

jobs:
  publish-release-sonatype:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 7.4

      - name: Get Project version
        id: get_version
        run: echo ::set-output name=VERSION::$(gradle properties --no-daemon --console=plain -q | grep "^version:" | awk '{printf $2}')

      - name: Decode
        run: |
          echo "${{secrets.SIGNING_SECRET_KEY_RING_FILE}}" > /tmp/secring.gpg.b64
          base64 -d /tmp/secring.gpg.b64 > /tmp/secring.gpg

      - name: Publish Release to Sonatype
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 7.4
          arguments: assemble publish -Psigning.keyId=${{secrets.SIGNING_KEY_ID}} -Psigning.password=${{secrets.SIGNING_PASSWORD}} -Psigning.secretKeyRingFile=/tmp/secring.gpg -PossrhUsername=${{secrets.SONATYPE_NEXUS_USERNAME}} -PossrhPassword=${{secrets.SONATYPE_NEXUS_PASSWORD}} --stacktrace

      - name: Create Release in Github
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ steps.get_version.outputs.VERSION }}
          release_name: ${{ steps.get_version.outputs.VERSION }}
          body: |
            Available in Sonatype SNAPSHOTs repository under:
            `io.reactiverse:aws-sdk:${{ steps.get_version.outputs.VERSION }}`
          draft: false
          prerelease: false
