name: CI-Snapshot
on:
  push:
    tags:
      - '*-SNAPSHOT'

jobs:
  publish-snapshot-sonatype:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 8.0

      - name: Get Project version
        id: get_version
        run: echo ::set-output name=VERSION::$(gradle properties --no-daemon --console=plain -q | grep "^version:" | awk '{printf $2}')

      - name: Publish Release to Sonatype
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 8.0
          arguments: assemble publish -PossrhUsername=${{secrets.SONATYPE_NEXUS_USERNAME}} -PossrhPassword=${{secrets.SONATYPE_NEXUS_PASSWORD}} --stacktrace

      - name: Create Release in Github
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ steps.get_version.outputs.VERSION }}
          release_name: ${{ steps.get_version.outputs.VERSION }}
          body: |
            Available in Sonatype SNAPSHOTs repository under:
            `io.reactiverse:aws-sdk:${{ steps.get_version.outputs.VERSION }}`
          draft: true
          prerelease: true
