# Always tests on every branch push / PR / master
name: CI-Test
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 8, 11, 17 ]
    name: "Run tests with JDK ${{ matrix.java }}"
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: ${{ matrix.java }}

      - name: Pre-Pull localstack image
        run: "docker pull localstack/localstack:0.14"


      - uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 7.4
          arguments: test -Dtests.integration=localstack
